--- 
- name: "installs wordpress"
  become: yes
  become_method: sudo
  hosts: all
  user: centos
  tasks: 
    - name: installation
      package: 
        name: "{{item}}"
        state: present
      with_items: 
        - epel-release
        - httpd
        - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        
    - name: enable remi-php73
      shell: "yum-config-manager --enable remi-php73"   

    - name: install php
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - php
        - mysql
        - php-mysql 

    - name: "download wordpress url"
      get_url: 
        url: https://www.wordpress.org/latest.tar.gz
        dest: /var/www/html/
        

    - name: unzip wordpress zip file
      unarchive: 
        src: /var/www/html/wordpress-5.4.1.tar.gz
        dest: /var/www/html/
        remote_src: yes    

    - name: move wordpress files to html folder
      shell: "mv /var/www/html/wordpress/* /var/www/html 2>/dev/null"
      become: yes
      become_method: sudo
      ignore_errors: yes
        
      
    -  name: "restart httpd"
       become: yes 
       become_method: sudo
       systemd: 
         name: httpd
         enabled: yes 
         state: restarted
         
  
